Importing the libraries

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Layer,Dense,Dropout

 Read the Dataset 

In [ ]:
data = pd.read_csv("drug200.csv")
data.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  DrugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  DrugY

In [ ]:
data.shape

(200, 6)

 Data Pre-processing

In [ ]:
data.isnull().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

Removing the Redundant attributes from the dataset


In [ ]:
data.drop(['TSH_measuerd',T3_measured','TT4_measured','T4U_measured','FTI_measured','TBG_measured','referral_source','patient_id'],'dtype:int64')

SyntaxError: ignored

Re-mapping the 'target' values to the diagnostic Group


In [ ]:
diagnoses={'A': 'hyperthyroid conditions',
           'B':'hyperthyroid conditions',
           'C':'hyperthyroid conditions',
           'D': 'hyperthyroid conditions',
           'E': 'hyperthyroid conditions',
           'F': 'hyperthyroid conditions',
           'G': 'hyperthyroid conditions',
           'H': 'hyperthyroid conditions',
           'I': 'binding protein',
           'J': 'binding protein',
           'K': 'general health',
           'L': 'replacement therapy',
           'M': 'replacement therapy',
           'N': 'replacement therapy',
           'O': 'antithyroid treatment',
           'P': 'antithyroid treatment',
           'Q': 'antithyroid treatment',
           'R': 'miscellaneous',
           'S': 'miscellaneous',
           'T': 'miscellaneous'}         


In [ ]:
data['target'] = data['target'].map(diagnoses)

KeyError: ignored

Dropping Null Values


In [ ]:
data.dropna(subset=['target'],inplace=True)

KeyError: ignored

In [ ]:
data['target'].value_counts()

KeyError: ignored

Checking the 'age' is there any above 100 and we drop the age>100

In [ ]:
data[data.age>100]

NameError: ignored

 Splitting the data x  and y 

In [ ]:
x=data.iloc[:,0:-1]
y=data.iloc[:,-1]

NameError: ignored

In [ ]:
x

NameError: ignored

In [ ]:
x['sex'].unique()

NameError: ignored

In [ ]:
x['sex'].replace(np,nan,'F',inplace=True)

NameError: ignored

In [ ]:
x['sex'].value_counts()

NameError: ignored

In [ ]:
x['age']=x['age'].astype('float')
x['TSH']=x['TSH'].astype('float')
x['T3']=x['T3'].astype('float')
x['TT4']=x['TT4'].astype('float')
x['T4U']=x['T4U'].astype('float')
x['FTI']=x['FTI'].astype('float')
x['TBG']=x['TBG'].astype('float')

NameError: ignored

In [ ]:
x.info()

NameError: ignored

 Handling Categorical Values

In [ ]:
from sklearn.preprocessing import ordinalEncoder,LabelEncoder

ImportError: ignored

In [ ]:
ordinal_encoder =OrdinalEncoder(dtype = 'int64')

NameError: ignored

In [ ]:
x.iloc[:,1:16] = ordinal_encoder.fit_transform(x.iloc[:,1:16])


NameError: ignored

In [ ]:
x

NameError: ignored

In [ ]:
x.replace(np.nan, '0',inplace=True)

NameError: ignored

In [ ]:
x

NameError: ignored

In [ ]:
label_encoder=LabelEncoder()
y_dt=label_encoder.fit_transform(y)
y=pd.DataFrame(y_dt,columns=['target'])
y

NameError: ignored

Splitting data into train and test

In [ ]:
x=data.iloc[:,0:-1]
y=data.iloc[:,-1]

NameError: ignored

In [ ]:
x

NameError: ignored

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=0)

NameError: ignored

In [ ]:
from imblearn.over_sampling import SMOTE
y_train.value_counts()

NameError: ignored

Handling Imbalanced Data

In [ ]:
os = SMOTE (random_state=0,k_neighbors=1)
x_bal,y_bal-os.fit_resample(x_train,y_train)
x_test_bal,y_test_bal-os.fit_resample (x_test,y_test)

NameError: ignored

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_balsc.fit_transform(x_bal)
x_test_bal sc.transform(x_test_bal)

SyntaxError: ignored

In [ ]:
x_bal

NameError: ignored

In [ ]:
columns-["age","sex", "on_thyroxine", "query_on_thyroxine', 'on antithyroid_meds', 'sick', 'pregnant', 'thyroid surgery', '1131_treatmer
x_test_bal pd.DataFrame(x_test_bal,columns-columns)
x_bal= pd.DataFrame(x_bal,columns-columns)
x_bal

SyntaxError: ignored

Performing Feature Importance

In [ ]:
from sklearn.inspection import permutation importance 
results = permutation_importance(rfr,x_bal,y_bal, scoring='accuracy")

SyntaxError: ignored

In [ ]:
feature_importance=['age', 'sex', 'on_thyroxine', 'query_on_thyroxine', 'on_antithyroid_meds', 'sick', 'pregnant', 'thyroid_surgery', 'I1
importance = results.importances_mean
importance = np.sort(importance)
for i, v in enumerate(importance):
i-feature_importance[i]
print('feature: {:<20} Score: {}'.format(i,v)
plt.figure(figsize-(10,10))
plt.bar(x=feature_importance, height = importance)
plt.xticks(rotation=30, ha='right')
plt.show()

SyntaxError: ignored

Selecting Output Columns

In [ ]:
x.head()

NameError: ignored

In [ ]:
x_bal.drop(['age','sex','on thyroxine','query_on_thyroxine','on_antithyroid_meds','sick','pregnant','thyroid_surgery','1131_treat
xst_bal.drop(['age', 'sex','on_thyroxine', 'query_on_thyroxine', 'on_antithyroid_meds', 'sick','pregnant', 'thyroid_surgery','I131',
x_bal.head()

SyntaxError: ignored

Exploratory Data Analysis

Descriptive analysis

In [ ]:
data.info()

NameError: ignored

Visual analysis

Checking Correlation

In [ ]:
import seaborn as sns
corrmat= x.corr()
f,ax = plt.subplots(figsize =(9,8))
sns.heatmap(corrmat, ax =ax, cnap ="YlGnBu", linewidths =0.1)

NameError: ignored

Model Building

Training the model in multiple algorithms

In [ ]:
from xgboost import XGBclassifier
xgb1 = XGBClassifier()
xgb1.fit(x_os,y_os)

ImportError: ignored

In [ ]:
y_pred = xgb1.predict(x_test_os)

SyntaxError: ignored

In [ ]:
print(classification_report(y_test_os,y_pred))

NameError: ignored

In [ ]:
accuracy_score(y_test_os,y_pred)

NameError: ignored

SVC model

In [ ]:
from sklearn.svm import Score
from sklearn.metrics import accuracy_score,classification_report
sv=SVC()
sv.fit(x_bal,y_bal)

ImportError: ignored

In [ ]:
SVC

NameError: ignored

In [ ]:
y_pred =sv.predict(h_test_hal)
print(classification_report(y_test_bal,y_pred))

NameError: ignored

In [ ]:
train_score =accuracy_score(y_bal,sv.predict(x_bal))
train_score

NameError: ignored

ANN Model

In [ ]:
In [68]:model = Sequential()
In [69]: model.add(Dense (units 128, activation='relu', input_shape=(10,)))
In [70]: model.add(Dense (units= 128, activation='relu', kernel_initializer="random_uniform')) 
         model.add(Dropout(0.2)) model.add(Dense (units 256, activation='relu, kernel_initializer="random_uniform"))
         model.add(Dropout (0.2)) model.add(Dense (units 128, activation='relu, kernel_initializer="random_uniform"))
In [71]: model.add(Dense (units - 1, activation-'signoid'))
In [72]: model.summary()
Model:"sequential"

SyntaxError: ignored

In [ ]:
In [73]: model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
In [75]: model.fit(x_bal,y_bal, validation_data=[x_test_bal, y_test_bal], epochs=15)

NameError: ignored

Testing the model

In [ ]:
In [115]: rfr1.predict([[0,0,0,0,0.000000, 0.0, 0.0,1.00, 0.0,40.0]])

NameError: ignored

In [ ]:
Out[115]: array([4])

NameError: ignored

In [ ]:
In [130]: sv.predict([[0,0,0,0,0.000000, 0.0,0.0,1.00, 0.0,0.0]])

NameError: ignored

In [ ]:
[130]:array([1])

SyntaxError: ignored

In [ ]:
In [143]: col = ['goitre', 'tumor', 'hypopituitary', 'psych', 'TSH', 'T3', 'TT4', 'T4U', 'FTI', 'TBG']
da = [[0,0,0,0,0.000000, 0.0, 0.0,1.00, 0.0,40.0]] 
da1 = pd.DataFrame(data = da, columns=col)
xgb1.predict(da1)

NameError: ignored

In [ ]:
Out [143]: array([4], dtype=int64)
In [140]: model.predict([[0,0,0,0,0.00, 0.0, 0.0,1.00, 0.0,0.0]])

NameError: ignored

In [ ]:
Out [140]: array([[1]], dtype=float32)

NameError: ignored

Performance Testing & Hyperparameter Tuning

Compare the model

In [ ]:
print(classification_report(y_test_bal,y_pred))

NameError: ignored

In [ ]:
train_score =accuracy_score(y_bal,rfrl.predict(x_bal))

NameError: ignored

In [ ]:
train_score

NameError: ignored

In [ ]:
y_pred=xgb.predict(x_test_bal)

NameError: ignored

In [ ]:
print(classification_report(y_test_bal,y_pred))

NameError: ignored

In [ ]:
train_score =accuracy_score(y_bal, xgb.predict(x_bal))
train_score

NameError: ignored

In [ ]:
y_pred =sv.predict(x_test_bal)
print(classification_report(y_test_bal,y_pred))

NameError: ignored

In [ ]:
train_score=accuracy_score(y_bal,sv.predict(x_bal))
train_score

NameError: ignored

In [ ]:
y_pred =model.predict(x_test_bal)

NameError: ignored

In [ ]:
print(classification_report(y_test_bal,y_pred))

NameError: ignored

In [ ]:
accuracy_score(y_test_bal,y_pred)

NameError: ignored

Comparing model accuracy before & after applying hyperparameter tuning

In [ ]:
params ={
    'c':[0.1,1,10,100,1000]
    'gamma':[1,0.1,0.01,0.001,0.0001],
    'kernal':['rbf','sqrt']
    
}

SyntaxError: ignored

In [ ]:
random_svc  =RandomizedSearchCV(sv,params,scoring='accurancy',cv=5,n_jobs=-1)
random_svc.fit(x_bal,y_bal)
random_svc.best_params_
{'kernal':'rbf','gamma':1,'c':1}

NameError: ignored

In [ ]:
svl=SVC(kernal='rbf',gamma=0.1,c=100)
svl.fit(x_bal,y_bal)

NameError: ignored

In [ ]:
SVC

NameError: ignored

In [ ]:
y_pred=svl.predict(x_test_bal)
print(classification_report(y_test_bal,y_pred))

NameError: ignored

In [ ]:
train_score=accuracy_score(y_bal,svl.predict(x_bal))
train_score

NameError: ignored

Saving the model as thyroid1_model.pkl

In [ ]:
import pickle
pickle.dump(svl,open('thyroid_1_model.pkl','wb'))
features=np.array([[0,0,0,0,0.000000,0.0,0.0,1.00,0.0,40.0]])
print(label_encoder.inverse_transform(xgb1.predict(features))


SyntaxError: ignored

In [ ]:
pickle.dump(label_encoder,open('label_encoder.pkl','wb'))
data['target'].unique()


NameError: ignored

In [ ]:
y['target'].unique()

NameError: ignored

Model Deployment

In [ ]:
import pickle
pickle.dump(svl,open('thyroid_1_model.pkl','wb'))

NameError: ignored